### ISSUE TITLE
Boxed Error when executing notebook

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#57]
Happens on

http://localhost:9000/template/statnlpbook/01_tasks/01_languagemodels

 but I feel I have seen this elsewhere as well...
```
[error] play - Cannot invoke the action, eventually got an error: java.util.concurrent.ExecutionException: Boxed Error
[error] application - 

! @6lnnbg7j1 - Internal server error, for (POST) [/compiler/scala] ->

play.api.Application$$anon$1: Execution exception[[AssertionError: assertion failed: failed to set value for moro_28n5d11e11gdn7adg6l2chfhhnmcc1bjne_1748803534Log: Error]]
	at play.api.Application$class.handleError(Application.scala:296) [play_2.11-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
	at play.api.Application$class.handleError(Application.scala:291) [play_2.11-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
Caused by: java.lang.AssertionError: assertion failed: failed to set value for moro_28n5d11e11gdn7adg6l2chfhhnmcc1bjne_1748803534Log: Error
	at scala.Predef$.assert(Predef.scala:165) ~[scala-library-2.11.4.jar:na]
	at controllers.ScalaIMainInterpreter.interpret(ScalaIMainInterpreter.scala:166) ~[classes/:na]
	at controllers.ScalaIMainInterpreter$$anonfun$execute$1.apply$mcVI$sp(ScalaIMainInterpreter.scala:211) ~[classes/:na]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166) ~[scala-library-2.11.4.jar:na]
	at controllers.ScalaIMainInterpreter.execute(ScalaIMainInterpreter.scala:209) ~[classes/:na]

```

**Comment by sameersingh** [comment]
I couldn't reproduce it (was too lazy to set up the statnlp notebook), but
I did add some debug code, so if it happens again, send me the terminal
output. If the terminal output looks useless, can you add
`settings.debug.value = true` on line 130 in ScalaIMainInterpreter.scala,
and let me know the output (the cells will look all messed up).

**Comment by riedelcastro** [comment]
They seem hard to reproduce, and I feel I have been running into different
variants of this when working with the statnlpbook (different error
messages, but somehow something state-dependent). The net effect is that I
keep on restarting quite regularly...

**Comment by riedelcastro** [comment]
Also, at some points scala cells stop showing output when changed and re-run. Unfortunately I have no idea when and why, so again this will be hard to reproduce.

**Comment by sameersingh** [comment]
Sure, will keep an eye on it, but paste whatever you see, if it's any
different from the previous output.

**Comment by parthaprotimkonwar** [comment]
`[error] play - Cannot invoke the action, eventually got an error: java.util.concurrent.ExecutionException: Boxed Error
[error] application - 

! @70j5dec1o - Internal server error, for (POST) [/update] ->

play.api.Application$$anon$1: Execution exception[[ExecutionException: Boxed Error]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.0.jar:2.2.0]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.0.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10-2.2.0.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10-2.2.0.jar:2.2.0]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [play_2.10-2.2.0.jar:2.2.0]
Caused by: java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:52) ~[scala-library.jar:na]
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:44) ~[scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:116) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58) [scala-library.jar:na]
	at scala.concurrent.Promise$class.failure(Promise.scala:107) [scala-library.jar:na]
java.lang.StackOverflowError: null
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.resolveEntityKey(AbstractRowReader.java:126) ~[hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.resolveEntityKey(AbstractRowReader.java:144) ~[hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.resolveEntityKey(AbstractRowReader.java:129) ~[hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.resolveEntityKey(AbstractRowReader.java:144) ~[hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.resolveEntityKey(AbstractRowReader.java:129) ~[hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.resolveEntityKey(AbstractRowReader.java:144) ~[hibernate-core-5.0.2.Final.jar:5.0.2.Final]
`
