### ISSUE TITLE
Moro live server keeps crashing

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#91]
Last message:

! @6nlc88fkh - Internal server error, for (GET) [/doc/gen_cache/01_tasks/0x_languagemodels] ->

play.api.Application$$anon$1: Execution exception[[ParserRuntimeException: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Heading/FirstOf/AtxHeading/OneOrMore/Sequence/AtxInline/Inline/Inline_Action1' at input position (line 2, pos 5):
### Sampling
    ^

org.pegdown.ParsingTimeoutException]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.8.jar:2.3.8]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
Caused by: org.parboiled.errors.ParserRuntimeException: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Heading/FirstOf/AtxHeading/OneOrMore/Sequence/AtxInline/Inline/Inline_Action1' at input position (line 2, pos 5):
### Sampling
    ^

org.pegdown.ParsingTimeoutException
        at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:366) ~[parboiled-java-1.1.6.jar:na]
        at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) ~[parboiled-core-1.1.6.jar:na]
        at org.parboiled.matchers.MemoMismatchesMatcher.match(MemoMismatchesMatcher.java:41) ~[parboiled-core-1.1.6.jar:na]
        at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) ~[parboiled-core-1.1.6.jar:na]
        at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) ~[parboiled-java-1.1.6.jar:na]
Caused by: org.pegdown.ParsingTimeoutException: null
        at org.pegdown.Parser.checkForParsingTimeout(Parser.java:1500) ~[pegdown-1.4.2.jar:1.4.2]
        at org.pegdown.Action$cxzDYiA1YTOH9nKV.run(Unknown Source) ~[na:1.4.2]
        at org.parboiled.matchers.ActionMatcher.match(ActionMatcher.java:96) ~[parboiled-core-1.1.6.jar:na]
        at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) ~[parboiled-core-1.1.6.jar:na]
        at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) ~[parboiled-java-1.1.6.jar:na]

**Comment by mbosnjak** [comment]
I got the same error a moment ago, and it seems to happen when changing between slides and the text a couple of times.
